name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]  # Use Node.js 20 explicitly, as it is now the default

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Grant execute permission to files (if necessary)
      run: chmod +x ./scripts/*  # Assuming you have shell scripts or executables in ./scripts

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
